/**
 *  @file   LArRecoND/include/LArRecoNDFormat.h
 *
 *  @brief  Header file defining the "LArRecoND" (HierarchyAnalysis output) format: to be read in by other modules to do track and shower fitting.
 *          Based on autogenerated ROOT code with Pandora-style edits (brought over from LArSP Format)
 *
 *  $Log: $
 */
#ifndef PANDORA_LAR_RECO_ND_FORMAT_H
#define PANDORA_LAR_RECO_ND_FORMAT_H 1

#include "TChain.h"
#include "TFile.h"
#include "TROOT.h"

// Header file for the classes stored in the TTree if any.
#include <vector>

namespace lar_nd_postreco
{

class LArRecoNDFormat
{
public:
    /**
     *  @brief  Constructor requiring TTree pointer
     *
     *  @param  tree The TTree pointer
     */
    LArRecoNDFormat(TTree *tree = nullptr);

    /**
     *  @brief  Destructor
     */
    virtual ~LArRecoNDFormat();

    /**
     *  @brief  Get the corresponding data entry
     *
     *  @param  entry The entry integer index
     *
     *  @return Total number of bytes read
     */
    virtual Int_t GetEntry(Long64_t entry);

    /**
     *  @brief  Initialise using the input TTree
     *
     *  @param  tree The input TTree
     */
    virtual void Init(TTree *tree);

    TTree *m_fChain;  ///< pointer to the analyzed TTree or TChain
    Int_t m_fCurrent; ///< current Tree number in a TChain

    // Declaration of leaf types
    Int_t m_event;
    Int_t m_subrun;
    Int_t m_run;
    Int_t m_unixTime;
    Int_t m_start_t;
    Int_t m_end_t;
    Int_t m_trigger;
    std::vector<int> *m_sliceID = nullptr;
    std::vector<int> *m_clusterID = nullptr;
    std::vector<float> *m_nuVtxX = nullptr;
    std::vector<float> *m_nuVtxY = nullptr;
    std::vector<float> *m_nuVtxZ = nullptr;
    std::vector<int> *m_n3DHits = nullptr;
    std::vector<int> *m_nUHits = nullptr;
    std::vector<int> *m_nVHits = nullptr;
    std::vector<int> *m_nWHits = nullptr;
    std::vector<int> *m_isShower = nullptr;
    std::vector<float> *m_trackScore = nullptr;
    std::vector<int> *m_recoPDG = nullptr;
    std::vector<int> *m_isRecoPrimary = nullptr;
    std::vector<float> *m_startX = nullptr;
    std::vector<float> *m_startY = nullptr;
    std::vector<float> *m_startZ = nullptr;
    std::vector<float> *m_endX = nullptr;
    std::vector<float> *m_endY = nullptr;
    std::vector<float> *m_endZ = nullptr;
    std::vector<float> *m_t0 = nullptr;
    std::vector<float> *m_dirX = nullptr;
    std::vector<float> *m_dirY = nullptr;
    std::vector<float> *m_dirZ = nullptr;
    std::vector<float> *m_centroidX = nullptr;
    std::vector<float> *m_centroidY = nullptr;
    std::vector<float> *m_centroidZ = nullptr;
    std::vector<float> *m_length1 = nullptr;
    std::vector<float> *m_length2 = nullptr;
    std::vector<float> *m_length3 = nullptr;
    std::vector<float> *m_energy = nullptr;
    std::vector<int> *m_recoHitId = nullptr;
    std::vector<int> *m_recoHitSliceId = nullptr;
    std::vector<int> *m_recoHitClusterId = nullptr;
    std::vector<float> *m_recoHitX = nullptr;
    std::vector<float> *m_recoHitY = nullptr;
    std::vector<float> *m_recoHitZ = nullptr;
    std::vector<float> *m_recoHitE = nullptr;
    std::vector<float> *m_recoHitT0 = nullptr;
    std::vector<int> *m_gotMatch = nullptr;
    std::vector<int> *m_mcPDG = nullptr;
    std::vector<long> *m_mcId = nullptr;
    std::vector<long> *m_mcLocalId = nullptr;
    std::vector<int> *m_isPrimary = nullptr;
    std::vector<int> *m_nSharedHits = nullptr;
    std::vector<float> *m_completeness = nullptr;
    std::vector<float> *m_purity = nullptr;
    std::vector<float> *m_mcEnergy = nullptr;
    std::vector<float> *m_mcPx = nullptr;
    std::vector<float> *m_mcPy = nullptr;
    std::vector<float> *m_mcPz = nullptr;
    std::vector<float> *m_mcVtxX = nullptr;
    std::vector<float> *m_mcVtxY = nullptr;
    std::vector<float> *m_mcVtxZ = nullptr;
    std::vector<float> *m_mcEndX = nullptr;
    std::vector<float> *m_mcEndY = nullptr;
    std::vector<float> *m_mcEndZ = nullptr;
    std::vector<int> *m_mcNuPDG = nullptr;
    std::vector<long> *m_mcNuId = nullptr;
    std::vector<int> *m_mcNuCode = nullptr;
    std::vector<float> *m_mcNuVtxX = nullptr;
    std::vector<float> *m_mcNuVtxY = nullptr;
    std::vector<float> *m_mcNuVtxZ = nullptr;
    std::vector<float> *m_mcNuE = nullptr;
    std::vector<float> *m_mcNuPx = nullptr;
    std::vector<float> *m_mcNuPy = nullptr;
    std::vector<float> *m_mcNuPz = nullptr;

    // List of branches
    TBranch *m_b_eventID = nullptr;
    TBranch *m_b_subrun = nullptr;
    TBranch *m_b_run = nullptr;
    TBranch *m_b_unixTime = nullptr;
    TBranch *m_b_start_t = nullptr;
    TBranch *m_b_end_t = nullptr;
    TBranch *m_b_trigger = nullptr;
    TBranch *m_b_sliceID = nullptr;
    TBranch *m_b_clusterID = nullptr;
    TBranch *m_b_nuVtxX = nullptr;
    TBranch *m_b_nuVtxY = nullptr;
    TBranch *m_b_nuVtxZ = nullptr;
    TBranch *m_b_n3DHits = nullptr;
    TBranch *m_b_nUHits = nullptr;
    TBranch *m_b_nVHits = nullptr;
    TBranch *m_b_nWHits = nullptr;
    TBranch *m_b_isShower = nullptr;
    TBranch *m_b_trackScore = nullptr;
    TBranch *m_b_recoPDG = nullptr;
    TBranch *m_b_isRecoPrimary = nullptr;
    TBranch *m_b_startX = nullptr;
    TBranch *m_b_startY = nullptr;
    TBranch *m_b_startZ = nullptr;
    TBranch *m_b_endX = nullptr;
    TBranch *m_b_endY = nullptr;
    TBranch *m_b_endZ = nullptr;
    TBranch *m_b_t0 = nullptr;
    TBranch *m_b_dirX = nullptr;
    TBranch *m_b_dirY = nullptr;
    TBranch *m_b_dirZ = nullptr;
    TBranch *m_b_centroidX = nullptr;
    TBranch *m_b_centroidY = nullptr;
    TBranch *m_b_centroidZ = nullptr;
    TBranch *m_b_length1 = nullptr;
    TBranch *m_b_length2 = nullptr;
    TBranch *m_b_length3 = nullptr;
    TBranch *m_b_energy = nullptr;
    TBranch *m_b_recoHitId = nullptr;
    TBranch *m_b_recoHitSliceId = nullptr;
    TBranch *m_b_recoHitClusterId = nullptr;
    TBranch *m_b_recoHitX = nullptr;
    TBranch *m_b_recoHitY = nullptr;
    TBranch *m_b_recoHitZ = nullptr;
    TBranch *m_b_recoHitE = nullptr;
    TBranch *m_b_recoHitT0 = nullptr;
    TBranch *m_b_gotMatch = nullptr;
    TBranch *m_b_mcPDG = nullptr;
    TBranch *m_b_mcId = nullptr;
    TBranch *m_b_mcLocalId = nullptr;
    TBranch *m_b_isPrimary = nullptr;
    TBranch *m_b_nSharedHits = nullptr;
    TBranch *m_b_completeness = nullptr;
    TBranch *m_b_purity = nullptr;
    TBranch *m_b_mcEnergy = nullptr;
    TBranch *m_b_mcPx = nullptr;
    TBranch *m_b_mcPy = nullptr;
    TBranch *m_b_mcPz = nullptr;
    TBranch *m_b_mcVtxX = nullptr;
    TBranch *m_b_mcVtxY = nullptr;
    TBranch *m_b_mcVtxZ = nullptr;
    TBranch *m_b_mcEndX = nullptr;
    TBranch *m_b_mcEndY = nullptr;
    TBranch *m_b_mcEndZ = nullptr;
    TBranch *m_b_mcNuPDG = nullptr;
    TBranch *m_b_mcNuId = nullptr;
    TBranch *m_b_mcNuCode = nullptr;
    TBranch *m_b_mcNuVtxX = nullptr;
    TBranch *m_b_mcNuVtxY = nullptr;
    TBranch *m_b_mcNuVtxZ = nullptr;
    TBranch *m_b_mcNuE = nullptr;
    TBranch *m_b_mcNuPx = nullptr;
    TBranch *m_b_mcNuPy = nullptr;
    TBranch *m_b_mcNuPz = nullptr;
};

//------------------------------------------------------------------------------------------------------------------------------------------

LArRecoNDFormat::LArRecoNDFormat(TTree *tree) :
    m_fChain(nullptr)
{
    // if parameter tree is not specified (or zero), connect the file
    // used to generate this class and read the Tree.
    if (tree == nullptr)
    {
        std::cout << "You are trying to instantiate LArRecoND format with a nullptr tree." << std::endl;
        std::abort();
    }
    Init(tree);
}

//------------------------------------------------------------------------------------------------------------------------------------------

LArRecoNDFormat::~LArRecoNDFormat()
{
    if (!m_fChain)
        return;
    delete m_fChain->GetCurrentFile();
}

//------------------------------------------------------------------------------------------------------------------------------------------

Int_t LArRecoNDFormat::GetEntry(Long64_t entry)
{
    // Read contents of entry.
    if (!m_fChain)
        return 0;
    return m_fChain->GetEntry(entry);
}

//------------------------------------------------------------------------------------------------------------------------------------------

void LArRecoNDFormat::Init(TTree *tree)
{
    // The Init() function is called when the selector needs to initialize
    // a new tree or chain. Typically here the branch addresses and branch
    // pointers of the tree will be set.
    // It is normally not necessary to make changes to the generated
    // code, but the routine can be extended by the user if needed.
    // Init() will be called many times when running on PROOF
    // (once per file to be processed).

    // Set branch addresses and branch pointers
    if (!tree)
        return;
    m_fChain = tree;
    m_fCurrent = -1;
    m_fChain->SetMakeClass(1);

    m_fChain->SetBranchAddress("event", &m_event, &m_b_eventID);
    m_fChain->SetBranchAddress("subRun", &m_subrun, &m_b_subrun);
    m_fChain->SetBranchAddress("run", &m_run, &m_b_run);
    m_fChain->SetBranchAddress("unixTime", &m_unixTime, &m_b_unixTime);
    m_fChain->SetBranchAddress("startTime", &m_start_t, &m_b_start_t);
    m_fChain->SetBranchAddress("endTime", &m_end_t, &m_b_end_t);
    m_fChain->SetBranchAddress("triggers", &m_trigger, &m_b_trigger);
    m_fChain->SetBranchAddress("sliceId", &m_sliceID, &m_b_sliceID);
    m_fChain->SetBranchAddress("clusterId", &m_clusterID, &m_b_clusterID);
    m_fChain->SetBranchAddress("nuVtxX", &m_nuVtxX, &m_b_nuVtxX);
    m_fChain->SetBranchAddress("nuVtxY", &m_nuVtxY, &m_b_nuVtxY);
    m_fChain->SetBranchAddress("nuVtxZ", &m_nuVtxZ, &m_b_nuVtxZ);
    m_fChain->SetBranchAddress("n3DHits", &m_n3DHits, &m_b_n3DHits);
    m_fChain->SetBranchAddress("nUHits", &m_nUHits, &m_b_nUHits);
    m_fChain->SetBranchAddress("nVHits", &m_nVHits, &m_b_nVHits);
    m_fChain->SetBranchAddress("nWHits", &m_nWHits, &m_b_nWHits);
    m_fChain->SetBranchAddress("isShower", &m_isShower, &m_b_isShower);
    m_fChain->SetBranchAddress("trackScore", &m_trackScore, &m_b_trackScore);
    m_fChain->SetBranchAddress("recoPDG", &m_recoPDG, &m_b_recoPDG);
    m_fChain->SetBranchAddress("isRecoPrimary", &m_isRecoPrimary, &m_b_isRecoPrimary);
    m_fChain->SetBranchAddress("startX", &m_startX, &m_b_startX);
    m_fChain->SetBranchAddress("startY", &m_startY, &m_b_startY);
    m_fChain->SetBranchAddress("startZ", &m_startZ, &m_b_startZ);
    m_fChain->SetBranchAddress("endX", &m_endX, &m_b_endX);
    m_fChain->SetBranchAddress("endY", &m_endY, &m_b_endY);
    m_fChain->SetBranchAddress("endZ", &m_endZ, &m_b_endZ);
    m_fChain->SetBranchAddress("t0", &m_t0, &m_b_t0);
    m_fChain->SetBranchAddress("dirX", &m_dirX, &m_b_dirX);
    m_fChain->SetBranchAddress("dirY", &m_dirY, &m_b_dirY);
    m_fChain->SetBranchAddress("dirZ", &m_dirZ, &m_b_dirZ);
    m_fChain->SetBranchAddress("centroidX", &m_centroidX, &m_b_centroidX);
    m_fChain->SetBranchAddress("centroidY", &m_centroidY, &m_b_centroidY);
    m_fChain->SetBranchAddress("centroidZ", &m_centroidZ, &m_b_centroidZ);
    m_fChain->SetBranchAddress("length1", &m_length1, &m_b_length1);
    m_fChain->SetBranchAddress("length2", &m_length2, &m_b_length2);
    m_fChain->SetBranchAddress("length3", &m_length3, &m_b_length3);
    m_fChain->SetBranchAddress("energy", &m_energy, &m_b_energy);
    m_fChain->SetBranchAddress("recoHitId", &m_recoHitId, &m_b_recoHitId);
    m_fChain->SetBranchAddress("recoHitSliceId", &m_recoHitSliceId, &m_b_recoHitSliceId);
    m_fChain->SetBranchAddress("recoHitClusterId", &m_recoHitClusterId, &m_b_recoHitClusterId);
    m_fChain->SetBranchAddress("recoHitX", &m_recoHitX, &m_b_recoHitX);
    m_fChain->SetBranchAddress("recoHitY", &m_recoHitY, &m_b_recoHitY);
    m_fChain->SetBranchAddress("recoHitZ", &m_recoHitZ, &m_b_recoHitZ);
    m_fChain->SetBranchAddress("recoHitE", &m_recoHitE, &m_b_recoHitE);
    m_fChain->SetBranchAddress("recoHitT0", &m_recoHitT0, &m_b_recoHitT0);
    m_fChain->SetBranchAddress("gotMatch", &m_gotMatch, &m_b_gotMatch);
    m_fChain->SetBranchAddress("mcPDG", &m_mcPDG, &m_b_mcPDG);
    m_fChain->SetBranchAddress("mcId", &m_mcId, &m_b_mcId);
    m_fChain->SetBranchAddress("mcLocalId", &m_mcLocalId, &m_b_mcLocalId);
    m_fChain->SetBranchAddress("isPrimary", &m_isPrimary, &m_b_isPrimary);
    m_fChain->SetBranchAddress("nSharedHits", &m_nSharedHits, &m_b_nSharedHits);
    m_fChain->SetBranchAddress("completeness", &m_completeness, &m_b_completeness);
    m_fChain->SetBranchAddress("purity", &m_purity, &m_b_purity);
    m_fChain->SetBranchAddress("mcEnergy", &m_mcEnergy, &m_b_mcEnergy);
    m_fChain->SetBranchAddress("mcPx", &m_mcPx, &m_b_mcPx);
    m_fChain->SetBranchAddress("mcPy", &m_mcPy, &m_b_mcPy);
    m_fChain->SetBranchAddress("mcPz", &m_mcPz, &m_b_mcPz);
    m_fChain->SetBranchAddress("mcVtxX", &m_mcVtxX, &m_b_mcVtxX);
    m_fChain->SetBranchAddress("mcVtxY", &m_mcVtxY, &m_b_mcVtxY);
    m_fChain->SetBranchAddress("mcVtxZ", &m_mcVtxZ, &m_b_mcVtxZ);
    m_fChain->SetBranchAddress("mcEndX", &m_mcEndX, &m_b_mcEndX);
    m_fChain->SetBranchAddress("mcEndY", &m_mcEndY, &m_b_mcEndY);
    m_fChain->SetBranchAddress("mcEndZ", &m_mcEndZ, &m_b_mcEndZ);
    m_fChain->SetBranchAddress("mcNuPDG", &m_mcNuPDG, &m_b_mcNuPDG);
    m_fChain->SetBranchAddress("mcNuId", &m_mcNuId, &m_b_mcNuId);
    m_fChain->SetBranchAddress("mcNuCode", &m_mcNuCode, &m_b_mcNuCode);
    m_fChain->SetBranchAddress("mcNuVtxX", &m_mcNuVtxX, &m_b_mcNuVtxX);
    m_fChain->SetBranchAddress("mcNuVtxY", &m_mcNuVtxY, &m_b_mcNuVtxY);
    m_fChain->SetBranchAddress("mcNuVtxZ", &m_mcNuVtxZ, &m_b_mcNuVtxZ);
    m_fChain->SetBranchAddress("mcNuE", &m_mcNuE, &m_b_mcNuE);
    m_fChain->SetBranchAddress("mcNuPx", &m_mcNuPx, &m_b_mcNuPx);
    m_fChain->SetBranchAddress("mcNuPy", &m_mcNuPy, &m_b_mcNuPy);
    m_fChain->SetBranchAddress("mcNuPz", &m_mcNuPz, &m_b_mcNuPz);
}

} // end namespace lar_nd_postreco

#endif
